### ISSUE TITLE
Disable Console logging

### ISSUE THREAD

**Issue by SankarGopalan** [lsilvadev/gRPCvsREST#1]
When console logging is disabled in appsettings file both gRPC and REST - you will find that REST is far superior to gRPC. This contradicts with the initial gains observed with logging enabled. What are your thoughts?

**Comment by lsilvadev** [comment]
I added this code in appsettings file both gRPC and REST:
```
"Console": {
    "LogLevel": {
      "Default": "None"
    }
  },
```

I executed the client. gRPC was superior to REST:

|         Method | IterationCount |       Mean |       Error |      StdDev |     Median |
|--------------- |--------------- |-----------:|------------:|------------:|-----------:|
| GrpcGetMessage |            100 |   588.3 us |    55.38 us |   149.72 us |   529.7 us |
| RestGetMessage |            100 | 6,031.7 us | 1,328.37 us | 3,874.93 us | 4,593.0 us |
| GrpcGetMessage |            200 |   555.4 us |    26.02 us |    72.96 us |   537.2 us |
| RestGetMessage |            200 | 2,243.8 us |   208.99 us |   568.57 us | 2,097.0 us |

Please describe how to reproduce this issue.

Thanks!

**Comment by SankarGopalan** [comment]
If you are running the client locally just set the following: "Microsoft": "Warning"

GrpcService - appSettings.Development.json 
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Grpc": "Information",
      "Microsoft": "Warning"
    }
  }
}

RestApi - appSettings.Development.json
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Warning"
    }
  }
}

**Comment by lsilvadev** [comment]
When console logging is disabled the Mean considerably reduces.

BenchmarkDotNet=v0.12.1, OS=macOS Catalina 10.15.4 (19E287) [Darwin 19.4.0]
Intel Core i5-7267U CPU 3.10GHz (Kaby Lake), 1 CPU, 4 logical and 2 physical cores
.NET Core SDK=3.0.101
  [Host]     : .NET Core 3.0.1 (CoreCLR 4.700.19.51502, CoreFX 4.700.19.51609), X64 RyuJIT
  DefaultJob : .NET Core 3.0.1 (CoreCLR 4.700.19.51502, CoreFX 4.700.19.51609), X64 RyuJIT

|         Method | IterationCount |     Mean |    Error |   StdDev |
|--------------- |--------------- |---------:|---------:|---------:|
| GrpcGetMessage |            100 | 234.4 us |  2.96 us |  3.40 us |
| RestGetMessage |            100 | 895.4 us | 15.37 us | 13.62 us |
| GrpcGetMessage |            200 | 230.2 us |  2.80 us |  2.48 us |
| RestGetMessage |            200 | 907.2 us | 17.81 us | 26.66 us |

 gRPC is superior to REST.

It's a good idea. Thanks a lot!

**Comment by lsilvadev** [comment]
Hi @SankarGopalan I did what you told me... I will close this issue!!

Thanks a lot!
